root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ."
  include_ext = ["go", "tpl", "tmpl", "html"] # file yang dipantau
  exclude_dir = ["assets", "tmp", "vendor"]   # folder yang di-skip
  exclude_file = []
  exclude_regex = ["_test\\.go"]              # skip file test
  delay = 1000                               # debounce delay (ms)

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
